### ISSUE TITLE
Consistency update for unit conversions in example applications

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudatExampleApplications#13]
In some of the example applications use is made of:
`mathematical_constants::PI / 180.0`
instead of:
`unit_conversions::convertDegreesToRadians`

Attached is a file indicating where these uses are replaced in the documentation. These adjustments also need to be incorporated in the bundle itself.
[ConsistentConversionAdjustmentsInDocumentation.txt](https://github.com/Tudat/tudatExampleApplications/files/1316752/ConsistentConversionAdjustmentsInDocumentation.txt)

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
