### ISSUE TITLE
PaGMOEx wait for idle infinite loop

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudatExampleApplications#21]
Hello,
In most PaGMO optimization examples, the evolution loops looks something like this:

```
for( int i = 1; i <= 100; i++ )
    {
        isl.evolve( );
        while( isl.status()!=pagmo::evolve_status::idle )
            isl.wait();
        // Rest of the code
```
The problem is that if there is an error in the evolve and using `isl.wait()`, the error is not raised, but suppressed. In addition, the evolve_status will either be busy_error and then idle_error., thus the while loop will never be false, making an infinite loop.

Possible solutions to that is to check for both idle and idle_error, and after the loop is done check for errors:
```
for(int i=1; i<=100; i++)
    {
        isl.evolve();
        while(isl.status()!=pagmo::evolve_status::idle &&
            isl.status()!=pagmo::evolve_status::idle_error){
                isl.wait();
        }
        isl.wait_check(); // Raises errors
        // Rest of the code
```
Or directly use `isl.wait_check();` to not suppress the error.
```
for(int i=1; i<=100; i++)
    {
        isl.evolve();
        while(isl.status()!=pagmo::evolve_status::idle){
                isl.wait_check();
            }
        // Rest of the code
```
Regards
Julius

**Comment by DominicDirkx** [comment]
Issue is adressed in pull request #23
