### ISSUE TITLE
Example application for propagating a single satellite subject to low-thrust force

### ISSUE THREAD

**Issue by mvandenbroeck** [Tudat/tudatExampleApplications#7]
I think it can be helpful for a lot of students to have an example application in Tudat of how to propagate a single satellite subject to a low-thrust force.
The low-thrust force should either be specified by a function (thrust as a function of time or position) or by loading a .txt file with the following four columns: Time, thrust in x-direction, thrust in y-direction, thrust in z-direction. In the latter case, the user should be able to specify the interpolator to be used for interpolating between the given values of the thrust force.

I'm willing to help setting up this example application.

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

This is absolutely a great idea.I guess we could adapt part of the application you are writing now as an example. 

If you push the current state of your code to your github account, I can directly have a look at it and see which (if any) changes would be needed to make an example application out of it,

Dominic

**Comment by mvandenbroeck** [comment]
Hi Dominic,

As soon as I have a working code, I'll push it to my github account.

Thanks,

Michael

**Comment by mvandenbroeck** [comment]
Hi Dominic,

Is the following commented code in the CMakeLists.txt of the satellitePropagatorExamples supposed to refer to the example application this issue is about?

`# Add thrust example
#add_executable(application_ThrustExample "${SRCROOT}/thrustAccelerationExample.cpp")
#setup_executable_target(application_ThrustExample "${SRCROOT}")
#target_link_libraries(application_ThrustExample ${TUDAT_APPLICATION_PROPAGATION_LIBRARIES} ${Boost_LIBRARIES} )
`

So then I'll make a file called thrustAccelerationExample.cpp in which a single spacecraft subject to a thrust-force is propagated.

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Yeah, this is a piece of code I once started on to showcase the thrust-in-velocity-vector-direction code. It's part of this commit, where you can see it:

https://github.com/Tudat/tudatExampleApplications/commit/2336e4ebe94c2c93ebd0ca1c3653e59a83b43b8e

I didn't get around to finishing it before updating the applications, so I removed it. 

The example you propose would be a lot more instructive, I think, as it provides a much more realistic shaping of the thrust vector.

**Comment by mvandenbroeck** [comment]
I would like to do a pull request to upload the first version of thrustAccelerationExample.cpp.
However, if I try to do so using Smartgit I get the following pop-up box:

![image](https://cloud.githubusercontent.com/assets/17763402/20312591/5ad7e244-ab54-11e6-9992-c7cf4ba4895f.png)

On my computer, the tudatExampleApplications folder is indicated as 'master' branch.

There is still an error on line 114 of thrustAccelerationExample.cpp that I wasn't able to solve. Maybe you can have a look at it?

Thanks,

Michael

**Comment by mvandenbroeck** [comment]
Hi Dominic,

I added the following function to referenceFrameTransformations.cpp to transform the thrust vector from the body-fixed TNW velocity frame to the planetocentric frame, which is defined as follows:

`Eigen::Quaterniond getPlanetocentricToTNWframeTransformationMatrix(
        const Eigen::Matrix< double, 6, 1 > spacecraftKeplerianState );
`

I found that in referenceFrameTransformations.cpp the input of the functions are usually angles instead of a state vector. So, would it perhaps be better to have the function defined as follows?

`Eigen::Quaterniond getPlanetocentricToTNWframeTransformationMatrix(
        const double eccentricy,
        const double inclination,
        const double argumentOfPeriapsis,
        const double longitudeOfAscendingNode,
        const double trueAnomaly
 );
`

If I understand you correctly, you also want to include the transformation from the inertial frame (I) to the planet-fixed frame, so that the function definition becomes:

`Eigen::Quaterniond getInertialToTNWframeTransformationMatrix(
        const Eigen::Matrix< double, 6, 1 > spacecraftKeplerianState,
        const Eigen::Matrix< double, 6, 1 > centralBodyKeplerianState );
`

Can you confirm this?
Tomorrow I will make a pull request of the corrected version.

Thanks a lot,


Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

For this transformation, we do actually need to use the Cartesian states of the two bodies (vehicle and central) as input. I think the algorithm is also best defined in terms ofbthese vectors,

Dominic

**Comment by DominicDirkx** [comment]
Hi Michael,

I've pushed some modifications to my branch of this issue:

https://github.com/DominicDirkx/tudat/tree/InterpolatedThrustSettings

Not everything is exactly it should be yet, style-wise, but the functionality you want should be operational, except for the frame transformation (now implemented as a dummy in Astrodynamics/ReferenceFrames/referenceFrameTransformations.h (line 431)

**Comment by mvandenbroeck** [comment]
Thanks, Dominic!

I completed the function in referenceFrameTransformations.cpp. I also added a function to go from the velocity based LVLH frame to a planetocentric frame using the Keplerian state vector of the satellite.

I will soon make a pull request of referenceFrameTransformation.cpp and the new version of unitTestReferenceFrameTransformations.cpp.

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

I wa playing with this mdoel a bit and notices that there is still a small bug in it... I'll let you know when it's fixed

**Comment by DominicDirkx** [comment]
I found some time to investigate the issue, and fixed the associated code (and added a small unit test). The interfaces have not changed, though.

**Comment by mvandenbroeck** [comment]
Thanks Dominic!

The last couple of days I've been reporting, but I'll have a look at it today.
I'll let you know when I'm finished.

Cheers,

Michael

**Comment by mvandenbroeck** [comment]
Hi Dominic,

When running tudat/Tudat/Astrodynamics/ReferenceFrames/UnitTests/unitTestReferenceFrameTransformations.cpp within the InterpolatedThrustSettingsBranch I get a runtime error at line 646:

`    Eigen::Vector3d expectedUnitVectorZ =
           ( Eigen::Vector3d( matrixToTest.block( 0, 0, 0, 3 ) ) ).cross(
                Eigen::Vector3d( matrixToTest.block( 0, 1, 0, 3 ) ) );`

which is called from line 756:

`testIsRotationMatrixRightHanded( nAxisAwayFromBodyMatrix );`

The application output is: 

`This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Running 10 test cases...
Assertion failed!

Program: C:\tudatBundle_mvdb\tudat\bin\unit_tests\test_ReferenceFrameTransformations.exe
File: C:/tudatBundle_mvdb/eigen/Eigen/src/Core/Block.h, Line 147

Expression: startRow >= 0 && blockRows >= 0 && startRow <= xpr.rows() - blockRows && startCol >= 0 && blockCols >= 0 && startCol <= xpr.cols() - blockCols`

Do you know how to fix this and why you didn't get the error?
Can the problem be caused by a difference in the version of Eigen?

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

Thanks for the check, I think you may be running in debug mode (?), which explains why it caught this error. I mixed up the indices in the .block call for the matrices. I've updated the code, let me know if it works for you now,

Cheers,

Dominic

**Comment by mvandenbroeck** [comment]
Hi Dominic,

Thanks for the fix! I runs smoothly now.
I was indeed running in debug mode, which made it possible to locate this error.
Thanks for the extensive unit tests. The only thing I corrected was a typo. I don't want to make a pull request for such a small change so here is what I changed:

find:
`positionDotProuctWithNTowardsBody`
replace with:
`positionDotProductWithNTowardsBody`

and

find:
`positionDotProuctWithNAwayFromBody`
replace with:
`positionDotProductWithNAwayFromBody`

Cheers,

Michael

**Comment by DominicDirkx** [comment]
Great, I've made the change to the code and committed it to the master.

**Comment by mvandenbroeck** [comment]
Hi Dominic,

I'm about to finish the thrustAccelerationExample.cpp in tudatExampleApplications but I get a segmentation fault at line 112 of the code in debug mode. It seems that the pointer is accessing memory that doesn't belong to it. 

![image](https://cloud.githubusercontent.com/assets/17763402/20754121/b348c996-b709-11e6-8a29-35b758aea29f.png)


[thrustAccelerationExample.txt](https://github.com/Tudat/tudatExampleApplications/files/621897/thrustAccelerationExample.txt)

(I had to change the extension to .txt to be able to upload it.

Is there a quick fix to this?

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

When you run the debugger, does it give you a stack trace? Debug -> start debugging -> start debugging? 

Does it run ok in release mode?

**Comment by mvandenbroeck** [comment]
I'm sorry for the delay, but I had to build the application again which took a long time.
It does give me the stack trace when running in debug mode.
It does not run in release mode. That just means normal mode, right? So CTRL+R.

The application output in release mode is:

`This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\tudatBundle_mvdb\tudatExampleApplications\satellitePropagatorExamples\bin\applications\application_ThrustAccelerationExample.exe
File: C:/tudatBundle_mvdb/eigen/Eigen/src/Core/DenseStorage.h, Line 109

Expression: (reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & (15)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"`

I'm looking through the stack now in Debug mode.

**Comment by mvandenbroeck** [comment]
Right before line 112 is executed:

`    // Creating settings for thrust force
    boost::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Vector3d > >
            thrustInterpolatorPointer = interpolators::createOneDimensionalInterpolator< double, Eigen::Vector3d >(
                thrustData, thrustInterpolatorSettingsPointer );`

the stack shows the following:

![image](https://cloud.githubusercontent.com/assets/17763402/20759435/3a29db9a-b71d-11e6-802b-c68367750956.png)

**Comment by DominicDirkx** [comment]
Hi Michael,

I think it's easiest if you drop by, and I can have a look at the code. Today or tomorrow after the Tudat meeting is fine

**Comment by mvandenbroeck** [comment]
http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html

**Comment by DominicDirkx** [comment]
Hi Michael,

The code runs fine on my computer (Ubuntu 14.04). I suspect that it's the same problem as this ancient Tudat issue:

http://tudat.tudelft.nl/issues/649

There is a bit of discussion on it here:

http://tudat.tudelft.nl/projects/tudat/wiki/Tips_and_tricks#Debugging-Eigen-assertion-errors

It seems that changing compiler may fix it, but I wouldn't recommend it. Try running in release mode, and check whether it works ok first,

Cheers,

Dominic

**Comment by mvandenbroeck** [comment]
Running the apolloCapsuleEntry in debug mode result in a runtime error too:

"
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\tudatBundle_mvdb\tudatExampleApplications\satellitePropagatorExamples\bin\applications\application_ApolloEntry.exe
File: C:/tudatBundle_mvdb/eigen/Eigen/src/Core/DenseStorage.h, Line 109

Expression: (reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & (15)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"
"

Changing the build mode from 'Debug' to 'Release' in TudatBundle/CMakeLists.txt solved the problem!
Both the apolloCapsuleEntry and the thrustAccelerationExample are working now.

Thanks for your help,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

I'm closing this issue, I've made some cosmetic changes to your code, and have added it to the update in pull request #9 . Thanks for all your work on this!

Cheers,

Dominic
